### ISSUE TITLE
no decimal/float coefficients?

### ISSUE THREAD

**Issue by ocramz** [laughedelic/sparse-lin-alg#5]
When I declare operands containing non-integer coefficients, solveLinear raises a "several potential instances", e.g. :1234: 

> let b = sparseList [1,3]
> :t b
b :: (Num α, Eq α) => SparseVector α
> let b' = sparseList [1,3.1]
> :t b'
b' :: (Fractional α, Eq α) => SparseVector α
> let a = sparseMx [[1,2],[2,1]]
> :t a
a :: (Num α, Eq α) => SparseMatrix α
> let a = sparseMx [[1.2,2],[2,1.2]]
> :t a
a :: (Fractional α, Eq α) => SparseMatrix α
> solveLinear a' b'

<interactive>:69:1:
    No instance for (Show α0) arising from a use of ‘print’
    The type variable ‘α0’ is ambiguous
    Note: there are several potential instances:
      instance Show Double -- Defined in ‘GHC.Float’
      instance Show Float -- Defined in ‘GHC.Float’
      instance (Integral a, Show a) => Show (GHC.Real.Ratio a)
        -- Defined in ‘GHC.Real’
      ...plus 29 others
    In a stmt of an interactive GHCi command: print it

Is this a bug or a feature? Is there a workaround for systems with non-integer coefficients?

**Comment by laughedelic** [comment]
Hi @ocramz! This is actually how it's [done](https://github.com/laughedelic/sparse-lin-alg/blob/master/Math/LinearAlgebra/Sparse/Algorithms/SolveLinear.hs#L41) — only for integer coefficients. I was using it for a [project](https://github.com/laughedelic/M-Cohomology) where worked particularly with integer coefficients, so here I implemented just a minimal set of necessary algorithms for that.

**Comment by ocramz** [comment]
thanks for the clarification, very inspiring work!

**Comment by laughedelic** [comment]
Thanks ") it's a pity though that I did't have time to maintain it. On the other hand there are already several sparse linear algebra libs for Haskell (~2-3 years ago there were none)...
